/*
 * This source file was generated by the Gradle 'init' task
 */

package org.example;
import org.example.Car;


public class App {
    public static void main(String[] args) {
        System.out.println("Welcome to Car Resale");
        
    }
}
